### ISSUE TITLE
Search page does not close properly/goes infinite

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#132]
This is pretty serious. The scraper keeps working but it is keeping the search page looping forever using resources and even KV store.

Looping this message
2021-04-25T07:28:48.234Z WARN  [SEARCH]: Cannot find place data in search.
2021-04-25T07:28:48.236Z INFO  [SEARCH]: Enqueued 0/0 places (correct location/total) + 0 ads --- https://www.google.com/maps/search/Inowroclaw+sklep+bio/@52.7861331,18.2493975,16z?hl=pl
2021-04-25T07:28:48.790Z WARN  [SEARCH]: Cannot find place data in search.
2021-04-25T07:28:48.794Z INFO  [SEARCH]: Enqueued 0/0 places (correct location/total) + 0 ads --- https://www.google.com/maps/search/E%C5%82k+wypo%C5%BCyczalnia+samochod%C3%B3w/@52.1477342,19.2882285,6z?hl=pl
2021-04-25T07:28:48.907Z WARN  [SEARCH]: Cannot find place data in search.

**Comment by metalwarrior665** [comment]
Should be fixed

**Comment by sergemarkin** [comment]
Looks like the issue is still there. I'm getting these loops quite often.
Any updates on that?
